version:  '3'
services:
  mysql_5_6:
    container_name: mysql_5_6
    ports:
      - "3806:3306"
    image: mysql:5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
      - "$PWD/mysql_5-6:/var/lib/mysql"
    networks:
      - net
  mysql_5_7:
    container_name: mysql_5_7
    ports:
      - "3809:3306"
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
      - "$PWD/mysql_5-7:/var/lib/mysql"
    networks:
      - net
  mysql_8_4_0:
    container_name: mysql_8_4_0
    ports:
      - "3809:3306"
    image: mysql:8.4.0
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
      - "$PWD/mysql_8_4_0:/var/lib/mysql"
    networks:
      - net
  mongo:
    image: mongo:6.0.1
    ports:
      - 27018:27017
    volumes:
      - "$PWD/mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - net

  postgres:
    container_name: postgres
    ports:
      - "5439:5432"
    image: postgres:14.11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    volumes:
      - "$PWD/postgres:/var/lib/postgresql/data"
    networks:
      - net

  redis_7_2_5:
    container_name: redis
    ports:
      - "6379:6379"
    image: redis:7.2.5-alpine
    volumes:
      - "$PWD/redis_7_2_5:/usr/local/etc/redis"
    networks:
      - net

networks:
  net:
